### PR TITLE
bug fix for escaped querystring values comming from github

### PR DESCRIPTION
**Pull request by doowb**
This is for the issue I just posted. I thought I'd be able to match the issue to the pull request, but I'm not sure how.

### CODE REVIEW

**Comment by danheberden** [comment]
If you mention the issue with a hash in front, like issue #5, then it should link up. Thanks for the fix! I think it'd be good to add tests for this, which would probably involve escaping the string and sending it using `http.request` (there is a test that does this now)

**Comment by doowb** [comment]
I missed that one, but I see it now. I was looking for one to make sure that it would work with an unescaped string. I'll update the tests to attempt with both escaped and unescaped.

**Comment by doowb** [comment]
Would be nice if there was something out there that could watch a github repo and build an npm package when something change... ;)

**Comment by danheberden** [comment]
Ah, I'd chalk it up to me being super new to having to publish to npm. I published v1.0.1 so it should be available for you :)

**Comment by danheberden** [comment]
And doobw, haha - wouldn't that be great if it could run code when a tag was added? Well played sir!

**Pull request merged**
