### PR TITLE
Crash when used as `pull_request` web hook

### PR DESCRIPTION
**Pull request by naholyr**
I wanted to use this library as a `pull_request` web hook.

When a PR is received, the server crashes with:

```
/home/naholyr/gith-test/node_modules/gith/lib/gith.js:191
    pusher: payload.pusher.name,
                          ^
TypeError: Cannot read property 'name' of undefined
    at Gith.simplifyPayload (/home/naholyr/gith-test/node_modules/gith/lib/gith.js:191:27)
    at EventEmitter.Gith (/home/naholyr/gith-test/node_modules/gith/lib/gith.js:108:24)
    at EventEmitter.emit (/home/naholyr/gith-test/node_modules/gith/node_modules/eventemitter2/lib/eventemitter2.js:310:21)
[…]
```

I guess the payload is not always the same, depending on hook type.

I'll provide a fix in the week-end :)

Note: To achieve this goal you have to deploy the hook using API, because the web UI only declares `push` hooks.

### CODE REVIEW

**Comment by danheberden** [comment]
Oh! I didn't even think about PRs - can you paste a copy of the payload from github for that? (or add it to the payloads in the test dir?)

**Comment by naholyr** [comment]
Yep:

``` javascript
{ number: 4,
  repository: 
   { events_url: 'https://api.github.com/repos/naholyr/gith/events',
     name: 'gith',
     assignees_url: 'https://api.github.com/repos/naholyr/gith/assignees{/user}',
     issue_comment_url: 'https://api.github.com/repos/naholyr/gith/issues/comments/{number}',
     git_tags_url: 'https://api.github.com/repos/naholyr/gith/git/tags{/sha}',
     open_issues_count: 4,
     size: 120,
     created_at: '2012-12-07T15:14:53Z',
     issues_url: 'https://api.github.com/repos/naholyr/gith/issues{/number}',
     has_wiki: true,
     forks_count: 1,
     subscription_url: 'https://api.github.com/repos/naholyr/gith/subscription',
     tags_url: 'https://api.github.com/repos/naholyr/gith/tags{/tag}',
     branches_url: 'https://api.github.com/repos/naholyr/gith/branches{/branch}',
     merges_url: 'https://api.github.com/repos/naholyr/gith/merges',
     clone_url: 'https://github.com/naholyr/gith.git',
     hooks_url: 'https://api.github.com/repos/naholyr/gith/hooks',
     git_commits_url: 'https://api.github.com/repos/naholyr/gith/git/commits{/sha}',
     private: false,
     forks_url: 'https://api.github.com/repos/naholyr/gith/forks',
     updated_at: '2012-12-07T15:32:18Z',
     contents_url: 'https://api.github.com/repos/naholyr/gith/contents/{+path}',
     watchers: 0,
     languages_url: 'https://api.github.com/repos/naholyr/gith/languages',
     ssh_url: 'git@github.com:naholyr/gith.git',
     fork: true,
     keys_url: 'https://api.github.com/repos/naholyr/gith/keys{/key_id}',
     url: 'https://api.github.com/repos/naholyr/gith',
     issue_events_url: 'https://api.github.com/repos/naholyr/gith/issues/events{/number}',
     labels_url: 'https://api.github.com/repos/naholyr/gith/labels{/name}',
     git_url: 'git://github.com/naholyr/gith.git',
     notifications_url: 'https://api.github.com/repos/naholyr/gith/notifications{?since,all,participating}',
     language: 'JavaScript',
     id: 7055082,
     svn_url: 'https://github.com/naholyr/gith',
     commits_url: 'https://api.github.com/repos/naholyr/gith/commits{/sha}',
     downloads_url: 'https://api.github.com/repos/naholyr/gith/downloads',
     pushed_at: '2012-12-07T15:30:45Z',
     comments_url: 'https://api.github.com/repos/naholyr/gith/comments{/number}',
     open_issues: 4,
     has_downloads: true,
     mirror_url: null,
     archive_url: 'https://api.github.com/repos/naholyr/gith/{archive_format}{/ref}',
     collaborators_url: 'https://api.github.com/repos/naholyr/gith/collaborators{/collaborator}',
     homepage: null,
     statuses_url: 'https://api.github.com/repos/naholyr/gith/statuses/{sha}',
     has_issues: false,
     trees_url: 'https://api.github.com/repos/naholyr/gith/git/trees{/sha}',
     full_name: 'naholyr/gith',
     git_refs_url: 'https://api.github.com/repos/naholyr/gith/git/refs{/sha}',
     description: 'simple node server that responds to github post-receive events with meaningful data',
     teams_url: 'https://api.github.com/repos/naholyr/gith/teams',
     forks: 1,
     stargazers_url: 'https://api.github.com/repos/naholyr/gith/stargazers',
     subscribers_url: 'https://api.github.com/repos/naholyr/gith/subscribers',
     watchers_count: 0,
     html_url: 'https://github.com/naholyr/gith',
     blobs_url: 'https://api.github.com/repos/naholyr/gith/git/blobs{/sha}',
     compare_url: 'https://api.github.com/repos/naholyr/gith/compare/{base}...{head}',
     milestones_url: 'https://api.github.com/repos/naholyr/gith/milestones{/number}',
     owner: 
      { avatar_url: 'https://secure.gravatar.com/avatar/396445b6e14727dcb6b3d6a66d52b567?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png',
        events_url: 'https://api.github.com/users/naholyr/events{/privacy}',
        gists_url: 'https://api.github.com/users/naholyr/gists{/gist_id}',
        gravatar_id: '396445b6e14727dcb6b3d6a66d52b567',
        received_events_url: 'https://api.github.com/users/naholyr/received_events',
        starred_url: 'https://api.github.com/users/naholyr/starred{/owner}{/repo}',
        url: 'https://api.github.com/users/naholyr',
        id: 214067,
        following_url: 'https://api.github.com/users/naholyr/following',
        subscriptions_url: 'https://api.github.com/users/naholyr/subscriptions',
        type: 'User',
        organizations_url: 'https://api.github.com/users/naholyr/orgs',
        repos_url: 'https://api.github.com/users/naholyr/repos',
        login: 'naholyr',
        followers_url: 'https://api.github.com/users/naholyr/followers' },
     contributors_url: 'https://api.github.com/repos/naholyr/gith/contributors',
     pulls_url: 'https://api.github.com/repos/naholyr/gith/pulls{/number}' },
  pull_request: 
   { number: 4,
     issue_url: 'https://github.com/naholyr/gith/issues/4',
     head: 
      { label: 'bonjourmodule:test3',
        repo: [Object],
        sha: 'abd633ff2744039e4bda1c697cea3d03152df3fc',
        ref: 'test3',
        user: [Object] },
     merged_by: null,
     created_at: '2012-12-07T15:50:13Z',
     changed_files: 1,
     merged: false,
     comments: 0,
     body: '',
     title: 'Test3',
     additions: 1,
     diff_url: 'https://github.com/naholyr/gith/pull/4.diff',
     updated_at: '2012-12-07T15:50:13Z',
     url: 'https://api.github.com/repos/naholyr/gith/pulls/4',
     _links: 
      { html: [Object],
        self: [Object],
        comments: [Object],
        issue: [Object],
        review_comments: [Object] },
     merge_commit_sha: '',
     review_comments_url: 'https://github.com/naholyr/gith/pull/4/comments',
     id: 3281103,
     commits_url: 'https://github.com/naholyr/gith/pull/4/commits',
     comments_url: 'https://api.github.com/repos/naholyr/gith/issues/4/comments',
     assignee: null,
     patch_url: 'https://github.com/naholyr/gith/pull/4.patch',
     mergeable_state: 'unknown',
     mergeable: null,
     milestone: null,
     closed_at: null,
     merged_at: null,
     commits: 2,
     user: 
      { avatar_url: 'https://secure.gravatar.com/avatar/396445b6e14727dcb6b3d6a66d52b567?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png',
        gists_url: 'https://api.github.com/users/naholyr/gists{/gist_id}',
        received_events_url: 'https://api.github.com/users/naholyr/received_events',
        events_url: 'https://api.github.com/users/naholyr/events{/privacy}',
        gravatar_id: '396445b6e14727dcb6b3d6a66d52b567',
        url: 'https://api.github.com/users/naholyr',
        starred_url: 'https://api.github.com/users/naholyr/starred{/owner}{/repo}',
        id: 214067,
        following_url: 'https://api.github.com/users/naholyr/following',
        subscriptions_url: 'https://api.github.com/users/naholyr/subscriptions',
        type: 'User',
        organizations_url: 'https://api.github.com/users/naholyr/orgs',
        repos_url: 'https://api.github.com/users/naholyr/repos',
        login: 'naholyr',
        followers_url: 'https://api.github.com/users/naholyr/followers' },
     deletions: 135,
     review_comments: 0,
     html_url: 'https://github.com/naholyr/gith/pull/4',
     state: 'open',
     base: 
      { label: 'naholyr:master',
        repo: [Object],
        sha: 'b493393b12a780735832a8ece5e16e723aef1318',
        ref: 'master',
        user: [Object] },
     review_comment_url: '/repos/naholyr/gith/pulls/comments/{number}' },
  sender: 
   { avatar_url: 'https://secure.gravatar.com/avatar/396445b6e14727dcb6b3d6a66d52b567?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png',
     events_url: 'https://api.github.com/users/naholyr/events{/privacy}',
     gists_url: 'https://api.github.com/users/naholyr/gists{/gist_id}',
     gravatar_id: '396445b6e14727dcb6b3d6a66d52b567',
     received_events_url: 'https://api.github.com/users/naholyr/received_events',
     starred_url: 'https://api.github.com/users/naholyr/starred{/owner}{/repo}',
     url: 'https://api.github.com/users/naholyr',
     id: 214067,
     following_url: 'https://api.github.com/users/naholyr/following',
     subscriptions_url: 'https://api.github.com/users/naholyr/subscriptions',
     type: 'User',
     organizations_url: 'https://api.github.com/users/naholyr/orgs',
     repos_url: 'https://api.github.com/users/naholyr/repos',
     login: 'naholyr',
     followers_url: 'https://api.github.com/users/naholyr/followers' },
  action: 'opened' }
```

I don't have time right now, but I may work on a solution in a few hours. Tell me if you want to fix it yourself so that we don't waste time ;)

**Comment by danheberden** [comment]
I can't get to it immediately, but will mention here when I start on it so that we aren't duping work - thanks for the help so far!

**Comment by naholyr** [comment]
Note that you can't absolutely identify from what hook type the payload comes from, there is no common key like `hook_type` or something. Bad move @github :(

I digged a bit more, and it may be a bit more complicated than a simple `if (pull_request) … else …`.

To be absolutely complete, here are the [possible hook types](http://developer.github.com/v3/repos/hooks/) and their [corresponding payload](http://developer.github.com/v3/activity/events/types/):
- `push` - _Any git push to a Repository._
  - `head` (_string_) - The SHA of the HEAD commit on the repository.
  - `ref` (_string_) - The full Git ref that was pushed. Example: “refs/heads/master”
  - `size` (_integer_) - The number of commits in the push.
  - `commits` (_array_) - The list of pushed commits.
  - `commits[][sha]` (_string_) - The SHA of the commit.
  - `commits[][message]` (_string_) - The commit message.
  - `commits[][author]` (_object_) - The git author of the commit.
  - `commits[][author][name]` (_string_) - The git author’s name.
  - `commits[][author][email]` (_string_) - The git author’s email address.
  - `commits[][url]` (_url_) - Points to the commit API resource.
  - `commits[][distinct]` (_boolean_) - Whether this commit is distinct from any that have been pushed before.
- `issues` - _Any time an Issue is opened or closed._
  - `action` (_string_) - The action that was performed: “opened”, “closed”, or “reopened”.
  - `issue` (_object_) - The issue itself.
- `issue_comment` - _Any time an Issue is commented on._
  - `action` (_string_) - The action that was performed on the comment.
  - `issue` (_object_) - The issue the comment belongs to.
  - `comment` (_object_) - The comment itself.
- `commit_comment` - _Any time a Commit is commented on._
  - `comment` (_object_) - The comment itself.
- `pull_request` - _Any time a Pull Request is opened, closed, or synchronized (updated due to a new push in the branch that the pull request is tracking)._
  - `action` (_string_) - The action that was performed: “opened”, “closed”, “synchronize”, or “reopened”.
  - `number` (_integer_) - The pull request number.
  - `pull_request` (_object_) - The pull request itself.
- `gollum` - _Any time a Wiki page is updated._
  - `pages` (_array_) - The pages that were updated.
  - `pages[][page_name]` (_string_) - The name of the page.
  - `pages[][title]` (_string_) - The current page title.
  - `pages[][action]` (_string_) - The action that was performed on the page.
  - `pages[][sha]` (_string_) - The latest commit SHA of the page.
  - `pages[][html_url]` (_string_) - Points to the HTML wiki page.
- `watch` - _Any time a User watches the Repository._
  - `action` (_string_) - The action that was performed.
- `download` - _Any time a Download is added to the Repository._
  - `download` (_object_) - The download that was just created.
- `fork` - _Any time a Repository is forked._
  - `forkee` (_object_) - The created repository.
- `fork_apply` - _Any time a patch is applied to the Repository from the Fork Queue._
  - `head` (_string_) - The branch name the patch is applied to.
  - `before` (_string_) - SHA of the repo state before the patch.
  - `after` (_string_) - SHA of the repo state after the patch.
- `member` - _Any time a User is added as a collaborator to a non-Organization Repository._
  - `member` (_object_) - The user that was added.
  - `action` (_string_) - The action that was performed: “added”.
- `public` - _Any time a Repository changes from private to public._
  - nothing to look here
- `status` - _Any time a Repository has a status update from the API_
  - not sure what we should expect here

As you can see, you cannot count on _any_ field in reality. If I'd like to use gith for a `public` web hook, then the payload would even be **empty**.

I think I'll propose two enhancements:
1. first, simply add all the checks to accept empty data.
2. on a second move, I'd like to refactor a bit to provide:
   - hook type identification based on payload
   - once hook type is known, a "simplified" payload depending on it

Let's focus only on first point yet.

**Comment by naholyr** [comment]
Here is the PR to _make it work_. With this the bug is fixed, no more crashes. There is still work to do to behave very nicely for every event types, but it's not the question here.

FYI, with this the simplified payload looks like this in case of a `pull_request` event:

``` javascript
   "files": {
      "all": [],
      "added": [],
      "deleted": [],
      "modified": []
   },
   "tag": "",
   "branch": "",
   "repo": "undefined/gith",
   "time": "2012-12-07T19:54:34Z",
   "urls": {
      "head": "",
      "branch": "",
      "tag": "",
      "repo": "https://api.github.com/repos/naholyr/gith"
   },
   "pusher": null,
   "matches": {}
```

Highly unreliable, like it's now said in README ;) But whatever, advanced user who wants to use specific events can still use `payload.original`. That lets more time to handle it really properly ;)

But alas, in all payloads (except classical `push`) there is very few informations… For example in the case of `pull_request`, we'll have to make a call to API to grab list of commits… I don't think this should be done transparently, and I'm not sure this is the role of your module. I believe those edge cases must not break the welcome simplicity of your work.

**Comment by danheberden** [comment]
Awesome - more time to work through the rest of the events would be nice. I _would_ like to offer API support for verification and auto install of web-hook uri's but that's definitely way down the road. The only thing I think we need in the above PR is a test with the payload. Is this something you have time to do?

**Comment by naholyr** [comment]
Aaaand it's done ;)

**Comment by danheberden** [comment]
You. Freaking. Rock.

**Pull request merged**
